export const errorDescriptions: Record<string, string> = {
  ELEMENT_NOT_FOUND: "No matching element was found for the selector, annotation, or lookup request.",
  ELEMENT_NOT_VISIBLE: "The target element exists but is not currently hittable because it is hidden, off-screen, or obscured.",
  TIMEOUT: "The operation did not complete before the timeout expired.",
  NAVIGATION_ERROR: "The browser could not complete the requested navigation.",
  INVALID_URL: "The provided URL is missing or malformed.",
  INVALID_SELECTOR: "The provided CSS selector is syntactically invalid.",
  INVALID_PARAM: "A provided parameter value is invalid.",
  INVALID_PARAMS: "One or more required parameters are missing or invalid.",
  NO_WEBVIEW: "No active browser renderer is attached yet.",
  NO_URL: "There is no current URL available for this action.",
  TAB_NOT_FOUND: "No open tab matched the requested tab ID.",
  PLATFORM_NOT_SUPPORTED: "This command is not implemented on the current platform or runtime.",
  BROWSER_NOT_REGISTERED: "The named local browser alias does not exist.",
  APP_NOT_INSTALLED: "Kelpie.app could not be found at the expected path.",
  BROWSER_LAUNCH_FAILED: "The local Kelpie app could not be launched successfully.",
  DEVICE_NOT_FOUND: "No discovered device matched the requested identifier.",
  NO_DEVICES: "No devices matched the discovery or filter criteria.",
  NO_DIALOG: "No JavaScript dialog is currently open.",
  RECORDING_IN_PROGRESS: "A recording or scripted session is already running and blocks the requested action.",
  MODEL_NOT_FOUND: "The requested model ID does not exist in the local catalog.",
  DOWNLOAD_FAILED: "The requested model download did not finish successfully.",
  NETWORK_ERROR: "The CLI could not reach the device over HTTP.",
};
