export const ErrorCode = {
  ELEMENT_NOT_FOUND: "ELEMENT_NOT_FOUND",
  ELEMENT_NOT_VISIBLE: "ELEMENT_NOT_VISIBLE",
  TIMEOUT: "TIMEOUT",
  NAVIGATION_ERROR: "NAVIGATION_ERROR",
  INVALID_SELECTOR: "INVALID_SELECTOR",
  INVALID_PARAMS: "INVALID_PARAMS",
  WEBVIEW_ERROR: "WEBVIEW_ERROR",
  IFRAME_ACCESS_DENIED: "IFRAME_ACCESS_DENIED",
  WATCH_NOT_FOUND: "WATCH_NOT_FOUND",
  ANNOTATION_EXPIRED: "ANNOTATION_EXPIRED",
  RECORDING_IN_PROGRESS: "RECORDING_IN_PROGRESS",
  PLATFORM_NOT_SUPPORTED: "PLATFORM_NOT_SUPPORTED",
  PERMISSION_REQUIRED: "PERMISSION_REQUIRED",
  SHADOW_ROOT_CLOSED: "SHADOW_ROOT_CLOSED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ApiError {
  code: string;
  message: string;
  diagnostics?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface ErrorResponse {
  success: false;
  error: ApiError;
}

export const ErrorHttpStatus: Record<ErrorCode, number> = {
  ELEMENT_NOT_FOUND: 404,
  ELEMENT_NOT_VISIBLE: 400,
  TIMEOUT: 408,
  NAVIGATION_ERROR: 502,
  INVALID_SELECTOR: 400,
  INVALID_PARAMS: 400,
  WEBVIEW_ERROR: 500,
  IFRAME_ACCESS_DENIED: 403,
  WATCH_NOT_FOUND: 404,
  ANNOTATION_EXPIRED: 400,
  RECORDING_IN_PROGRESS: 409,
  PLATFORM_NOT_SUPPORTED: 501,
  PERMISSION_REQUIRED: 403,
  SHADOW_ROOT_CLOSED: 403,
};
