import type { Platform } from "./device-types.js";

/** All browser-level MCP tool names */
export const BrowserMcpTools = [
  "kelpie_navigate",
  "kelpie_back",
  "kelpie_forward",
  "kelpie_reload",
  "kelpie_get_current_url",
  "kelpie_set_home",
  "kelpie_get_home",
  "kelpie_debug_screens",
  "kelpie_set_debug_overlay",
  "kelpie_get_debug_overlay",
  "kelpie_screenshot",
  "kelpie_get_dom",
  "kelpie_query_selector",
  "kelpie_query_selector_all",
  "kelpie_get_element_text",
  "kelpie_get_attributes",
  "kelpie_click",
  "kelpie_tap",
  "kelpie_fill",
  "kelpie_type",
  "kelpie_select_option",
  "kelpie_check",
  "kelpie_uncheck",
  "kelpie_scroll",
  "kelpie_scroll2",
  "kelpie_scroll_to_top",
  "kelpie_scroll_to_bottom",
  "kelpie_get_viewport",
  "kelpie_get_viewport_presets",
  "kelpie_get_device_info",
  "kelpie_get_capabilities",
  "kelpie_wait_for_element",
  "kelpie_wait_for_navigation",
  "kelpie_find_element",
  "kelpie_find_button",
  "kelpie_find_link",
  "kelpie_find_input",
  "kelpie_evaluate",
  "kelpie_toast",
  "kelpie_get_console_messages",
  "kelpie_get_js_errors",
  "kelpie_get_network_log",
  "kelpie_get_resource_timeline",
  "kelpie_clear_console",
  "kelpie_get_accessibility_tree",
  "kelpie_screenshot_annotated",
  "kelpie_click_annotation",
  "kelpie_fill_annotation",
  "kelpie_snapshot_3d_enter",
  "kelpie_snapshot_3d_exit",
  "kelpie_snapshot_3d_status",
  "kelpie_snapshot_3d_set_mode",
  "kelpie_snapshot_3d_zoom",
  "kelpie_snapshot_3d_reset_view",
  "kelpie_get_visible_elements",
  "kelpie_get_page_text",
  "kelpie_get_form_state",
  "kelpie_get_dialog",
  "kelpie_handle_dialog",
  "kelpie_set_dialog_auto_handler",
  "kelpie_get_tabs",
  "kelpie_new_tab",
  "kelpie_switch_tab",
  "kelpie_close_tab",
  "kelpie_get_iframes",
  "kelpie_switch_to_iframe",
  "kelpie_switch_to_main",
  "kelpie_get_iframe_context",
  "kelpie_get_cookies",
  "kelpie_set_cookie",
  "kelpie_delete_cookies",
  "kelpie_get_storage",
  "kelpie_set_storage",
  "kelpie_clear_storage",
  "kelpie_watch_mutations",
  "kelpie_get_mutations",
  "kelpie_stop_watching",
  "kelpie_query_shadow_dom",
  "kelpie_get_shadow_roots",
  "kelpie_get_clipboard",
  "kelpie_set_clipboard",
  "kelpie_set_geolocation",
  "kelpie_clear_geolocation",
  "kelpie_set_request_interception",
  "kelpie_get_intercepted_requests",
  "kelpie_clear_request_interception",
  "kelpie_show_keyboard",
  "kelpie_hide_keyboard",
  "kelpie_get_keyboard_state",
  "kelpie_resize_viewport",
  "kelpie_reset_viewport",
  "kelpie_set_viewport_preset",
  "kelpie_is_element_obscured",
  "kelpie_set_orientation",
  "kelpie_get_orientation",
  "kelpie_safari_auth",
  "kelpie_set_renderer",
  "kelpie_get_renderer",
  "kelpie_ai_status",
  "kelpie_ai_load",
  "kelpie_ai_unload",
  "kelpie_ai_ask",
  "kelpie_ai_record",
] as const;

export type BrowserMcpTool = (typeof BrowserMcpTools)[number];

export const BrowserToolUnsupportedPlatforms = {
  kelpie_ai_status: ["linux", "windows"],
  kelpie_ai_load: ["linux", "windows"],
  kelpie_ai_unload: ["linux", "windows"],
  kelpie_ai_ask: ["linux", "windows"],
  kelpie_ai_record: ["linux", "windows"],
  kelpie_show_keyboard: ["linux", "windows"],
  kelpie_hide_keyboard: ["linux", "windows"],
  kelpie_get_viewport_presets: ["linux", "windows"],
  kelpie_set_viewport_preset: ["linux", "windows"],
  kelpie_set_orientation: ["linux", "windows"],
  kelpie_safari_auth: ["linux", "windows"],
  kelpie_snapshot_3d_enter: ["linux", "windows"],
  kelpie_snapshot_3d_exit: ["linux", "windows"],
  kelpie_snapshot_3d_status: ["linux", "windows"],
  kelpie_snapshot_3d_set_mode: ["linux", "windows"],
  kelpie_snapshot_3d_zoom: ["linux", "windows"],
  kelpie_snapshot_3d_reset_view: ["linux", "windows"],
} satisfies Partial<Record<BrowserMcpTool, readonly Platform[]>>;

/** CLI-level MCP tools (discovery + group commands) */
export const CliMcpTools = [
  "kelpie_discover",
  "kelpie_list_devices",
  "kelpie_group_navigate",
  "kelpie_group_screenshot",
  "kelpie_group_find_button",
  "kelpie_group_fill",
  "kelpie_group_click",
  "kelpie_group_scroll2",
  "kelpie_group_find_element",
  "kelpie_group_find_link",
  "kelpie_group_find_input",
  "kelpie_group_a11y",
  "kelpie_group_dom",
  "kelpie_group_eval",
  "kelpie_group_console",
  "kelpie_group_errors",
  "kelpie_group_form_state",
  "kelpie_group_visible",
  "kelpie_group_keyboard_show",
  "kelpie_group_keyboard_hide",
  "kelpie_ai_models",
  "kelpie_ai_pull",
  "kelpie_ai_remove",
] as const;

export type CliMcpTool = (typeof CliMcpTools)[number];

export type McpToolName = BrowserMcpTool | CliMcpTool;

/** Map HTTP endpoint paths to MCP tool names */
export const httpToMcp: Record<string, BrowserMcpTool> = {
  "navigate": "kelpie_navigate",
  "back": "kelpie_back",
  "forward": "kelpie_forward",
  "reload": "kelpie_reload",
  "get-current-url": "kelpie_get_current_url",
  "set-home": "kelpie_set_home",
  "get-home": "kelpie_get_home",
  "debug-screens": "kelpie_debug_screens",
  "set-debug-overlay": "kelpie_set_debug_overlay",
  "get-debug-overlay": "kelpie_get_debug_overlay",
  "screenshot": "kelpie_screenshot",
  "get-dom": "kelpie_get_dom",
  "query-selector": "kelpie_query_selector",
  "query-selector-all": "kelpie_query_selector_all",
  "get-element-text": "kelpie_get_element_text",
  "get-attributes": "kelpie_get_attributes",
  "click": "kelpie_click",
  "tap": "kelpie_tap",
  "fill": "kelpie_fill",
  "type": "kelpie_type",
  "select-option": "kelpie_select_option",
  "check": "kelpie_check",
  "uncheck": "kelpie_uncheck",
  "scroll": "kelpie_scroll",
  "scroll2": "kelpie_scroll2",
  "scroll-to-top": "kelpie_scroll_to_top",
  "scroll-to-bottom": "kelpie_scroll_to_bottom",
  "get-viewport": "kelpie_get_viewport",
  "get-viewport-presets": "kelpie_get_viewport_presets",
  "get-device-info": "kelpie_get_device_info",
  "get-capabilities": "kelpie_get_capabilities",
  "wait-for-element": "kelpie_wait_for_element",
  "wait-for-navigation": "kelpie_wait_for_navigation",
  "find-element": "kelpie_find_element",
  "find-button": "kelpie_find_button",
  "find-link": "kelpie_find_link",
  "find-input": "kelpie_find_input",
  "evaluate": "kelpie_evaluate",
  "toast": "kelpie_toast",
  "get-console-messages": "kelpie_get_console_messages",
  "get-js-errors": "kelpie_get_js_errors",
  "get-network-log": "kelpie_get_network_log",
  "get-resource-timeline": "kelpie_get_resource_timeline",
  "clear-console": "kelpie_clear_console",
  "get-accessibility-tree": "kelpie_get_accessibility_tree",
  "screenshot-annotated": "kelpie_screenshot_annotated",
  "click-annotation": "kelpie_click_annotation",
  "fill-annotation": "kelpie_fill_annotation",
  "get-visible-elements": "kelpie_get_visible_elements",
  "get-page-text": "kelpie_get_page_text",
  "get-form-state": "kelpie_get_form_state",
  "get-dialog": "kelpie_get_dialog",
  "handle-dialog": "kelpie_handle_dialog",
  "set-dialog-auto-handler": "kelpie_set_dialog_auto_handler",
  "get-tabs": "kelpie_get_tabs",
  "new-tab": "kelpie_new_tab",
  "switch-tab": "kelpie_switch_tab",
  "close-tab": "kelpie_close_tab",
  "get-iframes": "kelpie_get_iframes",
  "switch-to-iframe": "kelpie_switch_to_iframe",
  "switch-to-main": "kelpie_switch_to_main",
  "get-iframe-context": "kelpie_get_iframe_context",
  "get-cookies": "kelpie_get_cookies",
  "set-cookie": "kelpie_set_cookie",
  "delete-cookies": "kelpie_delete_cookies",
  "get-storage": "kelpie_get_storage",
  "set-storage": "kelpie_set_storage",
  "clear-storage": "kelpie_clear_storage",
  "watch-mutations": "kelpie_watch_mutations",
  "get-mutations": "kelpie_get_mutations",
  "stop-watching": "kelpie_stop_watching",
  "query-shadow-dom": "kelpie_query_shadow_dom",
  "get-shadow-roots": "kelpie_get_shadow_roots",
  "get-clipboard": "kelpie_get_clipboard",
  "set-clipboard": "kelpie_set_clipboard",
  "set-geolocation": "kelpie_set_geolocation",
  "clear-geolocation": "kelpie_clear_geolocation",
  "set-request-interception": "kelpie_set_request_interception",
  "get-intercepted-requests": "kelpie_get_intercepted_requests",
  "clear-request-interception": "kelpie_clear_request_interception",
  "show-keyboard": "kelpie_show_keyboard",
  "hide-keyboard": "kelpie_hide_keyboard",
  "get-keyboard-state": "kelpie_get_keyboard_state",
  "resize-viewport": "kelpie_resize_viewport",
  "reset-viewport": "kelpie_reset_viewport",
  "set-viewport-preset": "kelpie_set_viewport_preset",
  "is-element-obscured": "kelpie_is_element_obscured",
  "set-orientation": "kelpie_set_orientation",
  "get-orientation": "kelpie_get_orientation",
  "safari-auth": "kelpie_safari_auth",
  "set-renderer": "kelpie_set_renderer",
  "get-renderer": "kelpie_get_renderer",
  "ai-status": "kelpie_ai_status",
  "ai-load": "kelpie_ai_load",
  "ai-unload": "kelpie_ai_unload",
  "ai-infer": "kelpie_ai_ask",
  "ai-record": "kelpie_ai_record",
  "snapshot-3d-enter": "kelpie_snapshot_3d_enter",
  "snapshot-3d-exit": "kelpie_snapshot_3d_exit",
  "snapshot-3d-status": "kelpie_snapshot_3d_status",
  "snapshot-3d-set-mode": "kelpie_snapshot_3d_set_mode",
  "snapshot-3d-zoom": "kelpie_snapshot_3d_zoom",
  "snapshot-3d-reset-view": "kelpie_snapshot_3d_reset_view",
};
