import type { Platform } from "./device-types.js";

/** All browser-level MCP tool names */
export const BrowserMcpTools = [
  "mollotov_navigate",
  "mollotov_back",
  "mollotov_forward",
  "mollotov_reload",
  "mollotov_get_current_url",
  "mollotov_set_home",
  "mollotov_get_home",
  "mollotov_debug_screens",
  "mollotov_set_debug_overlay",
  "mollotov_get_debug_overlay",
  "mollotov_screenshot",
  "mollotov_get_dom",
  "mollotov_query_selector",
  "mollotov_query_selector_all",
  "mollotov_get_element_text",
  "mollotov_get_attributes",
  "mollotov_click",
  "mollotov_tap",
  "mollotov_fill",
  "mollotov_type",
  "mollotov_select_option",
  "mollotov_check",
  "mollotov_uncheck",
  "mollotov_scroll",
  "mollotov_scroll2",
  "mollotov_scroll_to_top",
  "mollotov_scroll_to_bottom",
  "mollotov_get_viewport",
  "mollotov_get_device_info",
  "mollotov_get_capabilities",
  "mollotov_wait_for_element",
  "mollotov_wait_for_navigation",
  "mollotov_find_element",
  "mollotov_find_button",
  "mollotov_find_link",
  "mollotov_find_input",
  "mollotov_evaluate",
  "mollotov_toast",
  "mollotov_get_console_messages",
  "mollotov_get_js_errors",
  "mollotov_get_network_log",
  "mollotov_get_resource_timeline",
  "mollotov_clear_console",
  "mollotov_get_accessibility_tree",
  "mollotov_screenshot_annotated",
  "mollotov_click_annotation",
  "mollotov_fill_annotation",
  "mollotov_get_visible_elements",
  "mollotov_get_page_text",
  "mollotov_get_form_state",
  "mollotov_get_dialog",
  "mollotov_handle_dialog",
  "mollotov_set_dialog_auto_handler",
  "mollotov_get_tabs",
  "mollotov_new_tab",
  "mollotov_switch_tab",
  "mollotov_close_tab",
  "mollotov_get_iframes",
  "mollotov_switch_to_iframe",
  "mollotov_switch_to_main",
  "mollotov_get_iframe_context",
  "mollotov_get_cookies",
  "mollotov_set_cookie",
  "mollotov_delete_cookies",
  "mollotov_get_storage",
  "mollotov_set_storage",
  "mollotov_clear_storage",
  "mollotov_watch_mutations",
  "mollotov_get_mutations",
  "mollotov_stop_watching",
  "mollotov_query_shadow_dom",
  "mollotov_get_shadow_roots",
  "mollotov_get_clipboard",
  "mollotov_set_clipboard",
  "mollotov_set_geolocation",
  "mollotov_clear_geolocation",
  "mollotov_set_request_interception",
  "mollotov_get_intercepted_requests",
  "mollotov_clear_request_interception",
  "mollotov_show_keyboard",
  "mollotov_hide_keyboard",
  "mollotov_get_keyboard_state",
  "mollotov_resize_viewport",
  "mollotov_reset_viewport",
  "mollotov_is_element_obscured",
  "mollotov_set_orientation",
  "mollotov_get_orientation",
  "mollotov_safari_auth",
  "mollotov_set_renderer",
  "mollotov_get_renderer",
] as const;

export type BrowserMcpTool = (typeof BrowserMcpTools)[number];

export const BrowserToolUnsupportedPlatforms = {
  mollotov_show_keyboard: ["linux", "windows"],
  mollotov_hide_keyboard: ["linux", "windows"],
  mollotov_set_orientation: ["linux", "windows"],
  mollotov_safari_auth: ["linux", "windows"],
} satisfies Partial<Record<BrowserMcpTool, readonly Platform[]>>;

/** CLI-level MCP tools (discovery + group commands) */
export const CliMcpTools = [
  "mollotov_discover",
  "mollotov_list_devices",
  "mollotov_group_navigate",
  "mollotov_group_screenshot",
  "mollotov_group_find_button",
  "mollotov_group_fill",
  "mollotov_group_click",
  "mollotov_group_scroll2",
  "mollotov_group_find_element",
  "mollotov_group_find_link",
  "mollotov_group_find_input",
  "mollotov_group_a11y",
  "mollotov_group_dom",
  "mollotov_group_eval",
  "mollotov_group_console",
  "mollotov_group_errors",
  "mollotov_group_form_state",
  "mollotov_group_visible",
  "mollotov_group_keyboard_show",
  "mollotov_group_keyboard_hide",
] as const;

export type CliMcpTool = (typeof CliMcpTools)[number];

export type McpToolName = BrowserMcpTool | CliMcpTool;

/** Map HTTP endpoint paths to MCP tool names */
export const httpToMcp: Record<string, BrowserMcpTool> = {
  "navigate": "mollotov_navigate",
  "back": "mollotov_back",
  "forward": "mollotov_forward",
  "reload": "mollotov_reload",
  "get-current-url": "mollotov_get_current_url",
  "set-home": "mollotov_set_home",
  "get-home": "mollotov_get_home",
  "debug-screens": "mollotov_debug_screens",
  "set-debug-overlay": "mollotov_set_debug_overlay",
  "get-debug-overlay": "mollotov_get_debug_overlay",
  "screenshot": "mollotov_screenshot",
  "get-dom": "mollotov_get_dom",
  "query-selector": "mollotov_query_selector",
  "query-selector-all": "mollotov_query_selector_all",
  "get-element-text": "mollotov_get_element_text",
  "get-attributes": "mollotov_get_attributes",
  "click": "mollotov_click",
  "tap": "mollotov_tap",
  "fill": "mollotov_fill",
  "type": "mollotov_type",
  "select-option": "mollotov_select_option",
  "check": "mollotov_check",
  "uncheck": "mollotov_uncheck",
  "scroll": "mollotov_scroll",
  "scroll2": "mollotov_scroll2",
  "scroll-to-top": "mollotov_scroll_to_top",
  "scroll-to-bottom": "mollotov_scroll_to_bottom",
  "get-viewport": "mollotov_get_viewport",
  "get-device-info": "mollotov_get_device_info",
  "get-capabilities": "mollotov_get_capabilities",
  "wait-for-element": "mollotov_wait_for_element",
  "wait-for-navigation": "mollotov_wait_for_navigation",
  "find-element": "mollotov_find_element",
  "find-button": "mollotov_find_button",
  "find-link": "mollotov_find_link",
  "find-input": "mollotov_find_input",
  "evaluate": "mollotov_evaluate",
  "toast": "mollotov_toast",
  "get-console-messages": "mollotov_get_console_messages",
  "get-js-errors": "mollotov_get_js_errors",
  "get-network-log": "mollotov_get_network_log",
  "get-resource-timeline": "mollotov_get_resource_timeline",
  "clear-console": "mollotov_clear_console",
  "get-accessibility-tree": "mollotov_get_accessibility_tree",
  "screenshot-annotated": "mollotov_screenshot_annotated",
  "click-annotation": "mollotov_click_annotation",
  "fill-annotation": "mollotov_fill_annotation",
  "get-visible-elements": "mollotov_get_visible_elements",
  "get-page-text": "mollotov_get_page_text",
  "get-form-state": "mollotov_get_form_state",
  "get-dialog": "mollotov_get_dialog",
  "handle-dialog": "mollotov_handle_dialog",
  "set-dialog-auto-handler": "mollotov_set_dialog_auto_handler",
  "get-tabs": "mollotov_get_tabs",
  "new-tab": "mollotov_new_tab",
  "switch-tab": "mollotov_switch_tab",
  "close-tab": "mollotov_close_tab",
  "get-iframes": "mollotov_get_iframes",
  "switch-to-iframe": "mollotov_switch_to_iframe",
  "switch-to-main": "mollotov_switch_to_main",
  "get-iframe-context": "mollotov_get_iframe_context",
  "get-cookies": "mollotov_get_cookies",
  "set-cookie": "mollotov_set_cookie",
  "delete-cookies": "mollotov_delete_cookies",
  "get-storage": "mollotov_get_storage",
  "set-storage": "mollotov_set_storage",
  "clear-storage": "mollotov_clear_storage",
  "watch-mutations": "mollotov_watch_mutations",
  "get-mutations": "mollotov_get_mutations",
  "stop-watching": "mollotov_stop_watching",
  "query-shadow-dom": "mollotov_query_shadow_dom",
  "get-shadow-roots": "mollotov_get_shadow_roots",
  "get-clipboard": "mollotov_get_clipboard",
  "set-clipboard": "mollotov_set_clipboard",
  "set-geolocation": "mollotov_set_geolocation",
  "clear-geolocation": "mollotov_clear_geolocation",
  "set-request-interception": "mollotov_set_request_interception",
  "get-intercepted-requests": "mollotov_get_intercepted_requests",
  "clear-request-interception": "mollotov_clear_request_interception",
  "show-keyboard": "mollotov_show_keyboard",
  "hide-keyboard": "mollotov_hide_keyboard",
  "get-keyboard-state": "mollotov_get_keyboard_state",
  "resize-viewport": "mollotov_resize_viewport",
  "reset-viewport": "mollotov_reset_viewport",
  "is-element-obscured": "mollotov_is_element_obscured",
  "set-orientation": "mollotov_set_orientation",
  "get-orientation": "mollotov_get_orientation",
  "safari-auth": "mollotov_safari_auth",
  "set-renderer": "mollotov_set_renderer",
  "get-renderer": "mollotov_get_renderer",
};
